### ISSUE TITLE
[Tips]: SCALE

### ISSUE THREAD

**Issue by irabinovitch** [chris-short/devopsish.com#303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**  
URL:  http://www.socallinuxexpo.org
Title:  SCALE 19x

**Which service(s) is this request for?**  
SCALE is the largest community-run open-source and free software conference in North America. It is held annually in the greater Los Angeles area.  This summer it returns to an in person show at the LAX Hilton, July 28-31, 2022.

**Comment by chris-short** [comment]
Sorry. Forgot to add it this week. I've already stubbed out issue 270 with the event in there. Now I just have to remember to use it.

Thank you!

**Comment by chris-short** [comment]
It's in.
