### ISSUE TITLE
[Tips]: Robusta (Kubernetes Runbook Automation)

### ISSUE THREAD

**Issue by aantn** [chris-short/devopsish.com#305]
**Which service(s) is this request for?**  
[Robusta](https://github.com/robusta-dev/robusta)

**Tell us about what you're submitting**  
Robusta was built to make Kubernetes monitoring and alerting easier and less noisy, by adding extra features on-top of Prometheus, AlertManager, and Kubernetes itself. Those features include alert enrichment, runbook automation, and more.

**Additional context**  
Disclaimer: I'm one of the maintainers

**Comment by chris-short** [comment]
Done

**Comment by aantn** [comment]
Awesome, thanks!
