### ISSUE TITLE
[Tips]: 

### ISSUE THREAD

**Issue by jacobgranulate** [chris-short/devopsish.com#329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

URL:  https://gprofiler.io/
Title:  gProfiler - An open-source, continuous profiler for production – across any environment, at any scale.

**Which service(s) is this request for?**  

https://github.com/Granulate/gprofiler

**Tell us about what you're submitting**  

gProfiler enables any team to leverage cluster-wide profiling to investigate performance with minimal overhead.

By continuously analyzing code performance across your entire environment, you can optimize the most resource-consuming parts of your code, improve application performance, and reduce costs.

**Additional context**  

gProfiler is a free tool for performance and cost optimization, created by Granulate, an Intel company.

**Comment by chris-short** [comment]
Added to the share queue. May the odds be ever in your favor.
