### ISSUE TITLE
[Tips]: Adding hover effect on the navbar titles

### ISSUE THREAD

**Issue by ayush-wd** [chris-short/devopsish.com#330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**  
URL:  
Title:  

**Which service(s) is this request for?**  
Note: If this is a product, you must link the open source code for it. Not open source at all? That's a problem.

**Tell us about what you're submitting**  
What are some of the key points or benefits being suggested?

**Additional context**  
Anything else we should know?

**Attachments**  
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by chris-short** [comment]
The site code is open source. Feel free to take a whack at it.

**Comment by chris-short** [comment]
So... I've fixed it locally, but Netlify isn't playing along.

**Comment by chris-short** [comment]
Fixed!
